### ISSUE TITLE
Networking Class does not properly set fixed IPs

### ISSUE THREAD

**Issue by flakjacket95** [php-opencloud/openstack#103]
When creating a new Port, the user should be able to specify the desired fixedIPs for the new Port, Other SDKs usually use an array like set-up. The parameter would be an array of arrays, each specifying the subnet id and the IP address. Example: array(array('subnetId' => '75906d20-6625-11e4-9803-0800200c9a66', 'ipAddress' => '192.168.199.17'))

At this point, the API does not do anything with a fixedIPs paramter although the Port class has a field for the fixedIPs.

**Comment by haphan** [comment]
@flakjacket95 You are right, will push a fix momentary

**Comment by haphan** [comment]
Refer to PR #104 for prgress @flakjacket95
