### ISSUE TITLE
Way to set/update project quota/limits

### ISSUE THREAD

**Issue by RaySS1987** [php-opencloud/openstack#111]
I'm having a hard time finding a way to set or update project limits. Is this even supported in php-opencloud? If so, how do I do it? Thanks

**Comment by haphan** [comment]
@RaySS1987 There is a work-in-progress for updating project limits and quotas, see #113.

**Comment by haphan** [comment]
@RaySS1987  Setting project quota were just released in v2.0.7

Check it out and let us know if there is any issue.
