### ISSUE TITLE
List role assignments returns empty data

### ISSUE THREAD

**Issue by samuel4x4** [php-opencloud/openstack#117]
http://php-opencloudopenstack.readthedocs.io/en/latest/services/identity/v3/roles.html#list-role-assignments

foreach ($identity->listRoleAssignments() as $assignment)
   {
      $results[] = $assignment;
   }

It returns anytime this:

[
    {
        "resourceKey": null,
        "aliases": [],
        "role": null,
        "scope": null,
        "group": null,
        "user": null
    },
    {
        "resourceKey": null,
        "aliases": [],
        "role": null,
        "scope": null,
        "group": null,
        "user": null
    }
]

2 items with null values, even in Keystone the request returns content with different length, depending of the option used (e.g. ['projectId' => KEYSTONE_PROJECT_ID])

In Keystone access log I can see this:

Content length: 19513 
"GET /identity/v3/role_assignments HTTP/1.1" 200 19513 "-" "GuzzleHttp/6.2.1 curl/7.51.0 PHP/7.1.1"

OR

Content length: 1578 
"GET /identity/v3/role_assignments?scope.project.id=KEYSTONE_PROJECT_ID HTTP/1.1" 200 1578 "-" "GuzzleHttp/6.2.1 curl/7.51.0 PHP/7.1.1"

$assignment->retrieve() is not recognized. 

Any idea? Thanks.

**Comment by samuel4x4** [comment]
Hi @haphan, maybe you can help on this? Thanks!

**Comment by haphan** [comment]
@samuel4x4  Yep looks like it is a bug. Can you check out #118 and let me know if it works for you?

Thanks.

**Comment by samuel4x4** [comment]
Hi @haphan, your commit fixes the bug, thanks a lot! Can you tell me please when will it be available thru Composer with "php-opencloud/openstack": "^2.0"?

**Comment by haphan** [comment]
Bug fix released in 2.0.8
