### ISSUE TITLE
Wrong reference documentation link

### ISSUE THREAD

**Issue by samuel4x4** [php-opencloud/openstack#119]
Hello,

I noticed that in all pages the reference documentation URLs are not working:

For example, in http://php-opencloudopenstack.readthedocs.io/en/latest/services/identity/v3/services.html, section "Add Service", the url is 
http://refdocs.php-opencloud.com/OpenStack/Identity/v3/Service.html#method_createService

Network Error (dns_unresolved_hostname) 
Your requested host "refdocs.php-opencloud.com" could not be resolved by DNS.
For assistance, contact your network support team.

Thanks

**Comment by samuel4x4** [comment]
@haphan

**Comment by haphan** [comment]
thanks @samuel4x4 I will look into the issue

**Comment by haphan** [comment]
Issue is fixed @samuel4x4
