### ISSUE TITLE
Object download returning body with pointer at end of file when reading JSON

### ISSUE THREAD

**Issue by Y0lk** [php-opencloud/openstack#126]
When you call download() on an Object of a json file in object storage, the returned stream has its pointer at the end already. From what I understand, the download method calls populateFromResponse() on the response object. Inside the populateFromResponse() method, there is an exception in the case that the response is of content-type application/json. From what I understand it maps the json data into properties on the object, if the object has those properties. I have no idea what the purpose of this is, but since it calls getBody() on the response and casts it to a string, the __toString() method is called on the Guzzle Stream object, which in turn calls stream_get_contents() and therefore, the pointer is now at the end of the stream.

This causes an inconsistent behavior because you expect the pointer to be at the start of the returned stream from the download() method. 

In my case, I'm using Flysystem along with the SwiftAdapter (https://github.com/nimbusoftltd/flysystem-openstack-swift) to access the files. Therefore, when calling read() with Flysystem, the SwiftAdapter calls download() on the object, followed by getContents() on the stream. Since the pointer is at the end already, the returned content is empty and therefore, json files are always empty (whether you're copying or reading).

**Comment by Y0lk** [comment]
Any update on this?

**Comment by haphan** [comment]
@Y0lk Sounds like a bug to me. I will look into this issue today.

**Comment by Y0lk** [comment]
Thanks. We ended up fixing it in the flysystem-adapter by rewinding the stream first, but would be best to fix the real problem :)

**Comment by haphan** [comment]
@Y0lk A PR #134  is created to fix this issue.

Test script
```php
<?php //debug.php
$openstack = new OpenStack\OpenStack($paramsPackstack);

$objectStorage = $openstack->objectStoreV1();

$files = ['haphan/composer.json', 'haphan/README.md'];

foreach ($files as $f)
{
    /** @var \OpenStack\ObjectStore\v1\Models\Object $file */
    $file = $objectStorage->getContainer('phpopencloud')->getObject($f);

    echo sprintf("File %s \t\t Pointer %d". PHP_EOL, $f, $file->download()->tell());
}
```
Before the fix
```bash
haphan@hpbookpro:~/Projects/openstack$ php debug.php
File haphan/composer.json 		 Pointer 1991
File haphan/README.md 		 Pointer 0
```

After 
```bash
haphan@hpbookpro:~/Projects/openstack$ php debug.php
File haphan/composer.json 		 Pointer 0
File haphan/README.md 		 Pointer 0
```

**Comment by haphan** [comment]
@Y0lk PR has been merged to `master`

**Comment by Y0lk** [comment]
Thanks a lot for the fix!
