### ISSUE TITLE
Document how to use Identity v2 for authentication

### ISSUE THREAD

**Issue by ktwalrus** [php-opencloud/openstack#127]
Maybe I missed it, but this week I tried to use this SDK with OVH's Public Object Storage. OVH provides Identity v2 and it took me a long time to figure out how to authenticate against Identity v2 instead of the default Identity v3.

I finally got it working, but it would have helped to document this in the Official Documentation.

Could you please review my test case (below) to see if this is the best way to authenticate against Identity v2? Do I really need to repeat the authUrl in the options to the constructor?

If this is already documented, it is well hidden, at least from me.

Here is my working test case using OVH's OpenStack installation:

```
require 'vendor/autoload.php';

$openstack = new OpenStack\OpenStack( [
    'authUrl'           => 'https://auth.cloud.ovh.net/v2.0/',
    'region'            => 'BHS1',
    'username'          => '[REDACTED]',
    'password'          => '[REDACTED]',
    'tenantId'          => '[REDACTED]',
    'identityService'   => OpenStack\Identity\v2\Service::factory(
        new GuzzleHttp\Client( [
            'base_uri'  => OpenStack\Common\Transport\Utils::normalizeUrl( 'https://auth.cloud.ovh.net/v2.0/' ),
            'handler'   => GuzzleHttp\HandlerStack::create(),
        ] ) ),
    ] );

$service = $openstack->objectStoreV1();

foreach ($service->listContainers() as $container) {
    $container->retrieve();
    printf( "%s container has %d objects and %d bytes\n", $container->name, $container->objectCount, $container->bytesUsed );
}
```

**Comment by ktwalrus** [comment]
BTW, thinking about this more, why doesn't the framework auto-detect that OVH runs Identity v2 and automatically authenticate with this service?

Maybe the issue here is not with documentation but some bug in PHP OpenStack that fails to detect where to do authentication?

Here is the results when I run the same test above but don't set identityService explicitly:

```
PHP Fatal error:  Uncaught InvalidArgumentException: Either a user or token must be provided. in /www/SDKs/vendor/php-opencloud/openstack/src/Identity/v3/Models/Token.php:104
Stack trace:
#0 /www/SDKs/vendor/php-opencloud/openstack/src/Identity/v3/Service.php(58): OpenStack\Identity\v3\Models\Token->create(Array)
#1 /www/SDKs/vendor/php-opencloud/openstack/src/Identity/v3/Service.php(34): OpenStack\Identity\v3\Service->generateToken(Array)
#2 /www/SDKs/vendor/php-opencloud/openstack/src/Common/Service/Builder.php(96): OpenStack\Identity\v3\Service->authenticate(Array)
#3 /www/SDKs/vendor/php-opencloud/openstack/src/Common/Service/Builder.php(82): OpenStack\Common\Service\Builder->stockHttpClient(Array, 'ObjectStore\\v1')
#4 /www/SDKs/vendor/php-opencloud/openstack/src/OpenStack.php(157): OpenStack\Common\Service\Builder->createService('ObjectStore\\v1', Array)
#5 /www/SDKs/list-openstack.php(18): OpenStack\OpenStack->objectStoreV1()
#6 {main}
  thrown in /www/SDKs/vendor/php-opencloud/openstack/src/Identity/v3/Models/Token.php on line 104

Fatal error: Uncaught InvalidArgumentException: Either a user or token must be provided. in /www/SDKs/vendor/php-opencloud/openstack/src/Identity/v3/Models/Token.php on line 104

InvalidArgumentException: Either a user or token must be provided. in /www/SDKs/vendor/php-opencloud/openstack/src/Identity/v3/Models/Token.php on line 104

Call Stack:
    0.0004     351544   1. {main}() /www/SDKs/list-openstack.php:0
    0.0286     670816   2. OpenStack\OpenStack->objectStoreV1() /www/SDKs/list-openstack.php:18
    0.0286     671192   3. OpenStack\Common\Service\Builder->createService() /www/SDKs/vendor/php-opencloud/openstack/src/OpenStack.php:157
    0.0287     673304   4. OpenStack\Common\Service\Builder->stockHttpClient() /www/SDKs/vendor/php-opencloud/openstack/src/Common/Service/Builder.php:82
    0.0287     673304   5. OpenStack\Identity\v3\Service->authenticate() /www/SDKs/vendor/php-opencloud/openstack/src/Common/Service/Builder.php:96
    0.0287     673360   6. OpenStack\Identity\v3\Service->generateToken() /www/SDKs/vendor/php-opencloud/openstack/src/Identity/v3/Service.php:34
    0.0314     682664   7. OpenStack\Identity\v3\Models\Token->create() /www/SDKs/vendor/php-opencloud/openstack/src/Identity/v3/Service.php:58
```

**Comment by haphan** [comment]
@ktwalrus Detecting authentication service endpoint is not trivial. AFAIK, even Horizon (OpenStack's official GUI) does not support it; which I believe due to the major domain change between v2 and v3. Identity V3 is a true multi-tenancy model.

Having said that, I would love to look into the OVH's OpenStack implementation, and if needed, having a documentation specifically for OVH OS.

If you are able to provide a test account @ktwalrus, do PM me.

**Comment by ktwalrus** [comment]
I don't think OVH's OpenStack implementation is anything non-standard. They just run Identity v2 instead of Identity v3. I ran into this problem when upgrading from [https://github.com/rackspace/php-opencloud](https://github.com/rackspace/php-opencloud) which uses Identity v2 (according to the documentation).

I would love for OVH to upgrade their Public Cloud to Identity v3. For their Dedicated Cloud customers, they apparently configure 2 endpoints, one for v2 and the other for v3. But, Public Cloud customers are stuck with v2 only (as shown from their catalog listing).

So, when I upgraded to the PHP-OpenStack API in this repo, it took me quite a while to recognize that the documentation for this API assumes you have Identity v3.

Anyway, I see two possible resolutions for this issue:

1. Document how to use PHP-OpenStack with Identity v2, or
1. Have PHP-OpenStack auto-detect that the authURL given is an Identity v2 endpoint and create the 'identityService' object as a v2 object automatically.

I think the solution of simply documenting how to use PHP-OpenStack with Identity v2 is probably the way to go (and easiest for you to implement since it is just documentation update that is needed).

**Comment by haphan** [comment]
> Have PHP-OpenStack auto-detect that the authURL given is an Identity v2 endpoint and create the 'identityService' object as a v2 object automatically.

Endpoints cannot be auto-detected though there is `common convention` , e.g. using port 5000 for identity and such but there is guarantee it is valid. For example, my production Openstack is using a different port.

I prefer SDK to explicitly require this endpoint URL.

> Document how to use PHP-OpenStack with Identity v2

This is the way to go.

**Comment by julienfastre** [comment]
Hi,

I encountered exactly the same problem.

I find that the documentation is well done, but I think it misses a page where all configurations options are described. The configuration options in docblock (https://github.com/php-opencloud/openstack/blob/master/src/OpenStack.php#L25) are different than those used in documentation (button "show auth code"). I am still quite confused about which one to use.

I am still not yet confident to propose a PR for resolving this issue...

Regards,

**Comment by haphan** [comment]
Documentation for authentication using `v2.0` has been added.

http://php-openstack-sdk.readthedocs.io/en/identity-v2/services/identity/v2/authentication.html

Close issue for now but feel free to comment to reopen the case.
