### ISSUE TITLE
Implement OpenStack's LBAAS

### ISSUE THREAD

**Issue by laszlof** [php-opencloud/openstack#132]
It appears that this library does not support OpenStack's LoadBalancer As A Service functionality. As this is something we plan on using in the near future, I will begin work on implementing this into the current code base.

I wanted to create this issue simply to inform the core team of my intentions to work on this feature. A PR will be submitted once it has been fully tested and is functional.

**Comment by haphan** [comment]
thank you @laszlof

**Comment by laszlof** [comment]
No problem @haphan. Thanks for merging so quickly. Look forward to using this in production.
