### ISSUE TITLE
Adding a method $container->hasObject

### ISSUE THREAD

**Issue by julienfastre** [php-opencloud/openstack#137]
Hi,

In my project, I have to check at different places that an object exists in a object store container.

I use this function : 

```php
protected function hasObject(
    \OpenStack\ObjectStore\v1\Models\Container $container, 
    $objectName
) {
    try {
        $container->getObject($objectName)->retrieve();
    } catch (\OpenStack\Common\Error\BadResponseError $e) {
        if ($e->getResponse()->getStatusCode() === 404) {
            return false;
        } else {
            // the error is something else. Throw the error again...
            throw $e;
        }
    }
    
    return true;
}
```

It would be very nice if this function was available in the php-opencloud api, and that we could use it like this : 

```
$container->hasObject($objectName);
```

Regards,

**Comment by jamiehannaford** [comment]
We already have `objectExists`:

https://github.com/php-opencloud/openstack/blob/master/src/ObjectStore/v1/Models/Container.php#L162

**Comment by haphan** [comment]
Close as question is answered.

**Comment by julienfastre** [comment]
Thanks !
