### ISSUE TITLE
Opcache issues

### ISSUE THREAD

**Issue by ischenko** [php-opencloud/openstack#158]
Good day!

Enabling OpCache breaks the library. It turns out that part of the code relies on docblocks.
https://github.com/php-opencloud/openstack/blob/5027caab5271ab5cc7370242c827b2847ef8d2c5/src/Common/Resource/AbstractResource.php#L120-L131
As a temporary solution we had to enable `opcache.save_comments=1` on production servers (which is not good).

Is it possible to refactor the code and get rid of usage of docblocks in the library?

**Comment by haphan** [comment]
> we had to enable opcache.save_comments=1 on production servers (which is not good).

Why not good @ischenko ? I don't see any benefit of doing so except saving a few bytes of the compiled opcode. There is a good reason why the default value is `1`.

Official docs:
> Disabling this configuration directive may break applications and frameworks that rely on comment parsing for annotations, including Doctrine, Zend Framework 2 and PHPUnit.

**Comment by ischenko** [comment]
> Doctrine, Zend Framework 2 and PHPUnit.

If I'm not wrong Doctrine, Zend Framework 2 and PHPUnit don't enforce you to enable save_comments and can work without it. PHPUnit is not even designed to be used in production environment.

> I don't see any benefit of doing so except saving a few bytes of the compiled opcode

Comments are strings and stored as a strings. Our project has over 17k of php files. Average comment block is about 120 bytes long (some blocks are really big), assume that half of files are tests and other unused files in a production environment. Roughly we have 1MB of wasted memory I would prefer to spend it to more useful stuff.

I don't want to continue a Holy War about using of annotations, so in returning to original request: Is it possible to refactor the code and get rid of usage of docblocks in the library?

**Comment by haphan** [comment]
> Is it possible to refactor the code and get rid of usage of docblocks in the library?

No, we won't spend effort trying to optimize your 1MB of memory.

**Comment by jamiehannaford** [comment]
I agree with @haphan.

@ischenko While I understand your concern, saving 1MB of memory does not represent enough of a reason for us to refactor a core part of the library.

**Comment by ischenko** [comment]
@jamiehannaford please see  the branch https://github.com/ischenko/openstack/commits/nodockblocks there are two commits.

 - 1a9465772852ab507b243ecc9b7aecab838b60ca  contains changes that remove usage of dockblocks
 - 9a9089887ea98ca46722782b798298058b136ad4 these changes made in separate commit because I'm not sure if it is right. Annotations states that these properties should be a lists but in unit tests there are assertions that they should be objects. 

Most likely it is a bug in original code, for example:
`tests/unit/Networking/v2/Models/LoadBalancerPoolTest.php(53)`: here response will return following data for `listeners` property: 
`
        "listeners": [
            {
                "id": "39de4d56-d663-46e5-85a1-5b9d5fa17829"
            }
        ]
`
and instead of a list, property `listeners` will contain instance of class `\OpenStack\Networking\v2\Models\LoadBalancerListener` and most likely all its properties will be `NULL`.

So second commit was created just to make fix quickly in case if it is really a bug.

If it is good for you do let me know and I will create pull request.

**Comment by ischenko** [comment]
see #159
