### ISSUE TITLE
How find the tenant id of current user ?

### ISSUE THREAD

**Issue by BorderCloud** [php-opencloud/openstack#160]
Hello
I try to find the tenantid for the function addMember but I don't found the solution.

```php
$user1 = new OpenStack\OpenStack([...]);

$user2 = new OpenStack\OpenStack([...]);

$member = $user1->imagesV2()
                    ->getImage('{imageId}')
                    ->addMember(user2->?????->tenantID);
```
How find the tenantid of user2 with object  OpenStack ? 

Thanks

**Comment by haphan** [comment]
'$user->defaultProjectId' to retrieve default tenant ID or '$user->listProjects' to retrieve all tenants of that user

**Comment by BorderCloud** [comment]
$user->defaultProjectId => E‌rror : Undefined property
:(

I found a bad solution : read in the token via a request curl without the lib.

**Comment by haphan** [comment]
@BorderCloud  Retrieving project ID via authentication token can achieve via `generateToken`

```php
$params = []; //Your openstack params

$openstack = new \OpenStack\OpenStack($params);
$token = $openstack->identityV3()->generateToken($params);
echo "Project id is {$token->project}";
```
