### ISSUE TITLE
Getting a 404 error (https://auth.cloud.ovh.net/v2.0/auth/tokens) while creating object for open stack class

### ISSUE THREAD

**Issue by thatipelli69** [php-opencloud/openstack#161]
How can I solve this below issue? 

We are using OVH cloud and we got these credentials from horizon dashboard.

**Code used for it:**

$openstack = new OpenStack\OpenStack ( [ 
				'authUrl' => 'https://auth.cloud.ovh.net/v2.0',
				'region' => 'GRA3',
				'user' => [ 
						'id' => 'XXXXXXXXXXXXX',
						'password' => 'XXXXXXXXXXXXXX' 
				],
				'scope' => [ 
						'project' => [ 
								'id' => 'XXXXXXXXX' 
						] 
				] 
		] );

$service = $openstack->objectStoreV1();
		foreach ($service->listContainers() as $container) {
			/** @var $container \OpenStack\ObjectStore\v1\Models\Container */
			var_dump($container);
		}

Response : 

13 Oct 2017 12:52:56 [22762] CRIT [::1]:Client error: `POST https://auth.cloud.ovh.net/v2.0/auth/tokens` resulted in a `404 Not Found` response:
{"error": {"message": "The resource could not be found.", "code": 404, "title": "Not Found"}}

13 Oct 2017 12:52:56 [22762] CRIT [::1]:#0 /var/www/test_v3_current/test-pro-web/library/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /var/www/test_v3_current/test-pro-web/library/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /var/www/test_v3_current/test-pro-web/library/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /var/www/test_v3_current/test-pro-web/library/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /var/www/test_v3_current/test-pro-web/library/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /var/www/test_v3_current/test-pro-web/library/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /var/www/test_v3_current/test-pro-web/library/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /var/www/test_v3_current/test-pro-web/library/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /var/www/test_v3_current/test-pro-web/library/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /var/www/test_v3_current/test-pro-web/library/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Promise\Promise->wait()
#10 /var/www/test_v3_current/test-pro-web/library/vendor/php-opencloud/openstack/src/Common/Api/OperatorTrait.php(115): GuzzleHttp\Client->request('POST', 'auth/tokens', Array)
#11 /var/www/test_v3_current/test-pro-web/library/vendor/php-opencloud/openstack/src/Common/Api/OperatorTrait.php(123): OpenStack\Common\Resource\OperatorResource->sendRequest(Object(OpenStack\Common\Api\Operation), Array)
#12 /var/www/test_v3_current/test-pro-web/library/vendor/php-opencloud/openstack/src/Identity/v3/Models/Token.php(107): OpenStack\Common\Resource\OperatorResource->execute(Array, Array)
#13 /var/www/test_v3_current/test-pro-web/library/vendor/php-opencloud/openstack/src/Identity/v3/Service.php(58): OpenStack\Identity\v3\Models\Token->create(Array)
#14 /var/www/test_v3_current/test-pro-web/library/vendor/php-opencloud/openstack/src/Identity/v3/Service.php(34): OpenStack\Identity\v3\Service->generateToken(Array)
#15 /var/www/test_v3_current/test-pro-web/library/vendor/php-opencloud/openstack/src/Common/Service/Builder.php(96): OpenStack\Identity\v3\Service->authenticate(Array)
#16 /var/www/test_v3_current/test-pro-web/library/vendor/php-opencloud/openstack/src/Common/Service/Builder.php(82): OpenStack\Common\Service\Builder->stockHttpClient(Array, 'ObjectStore\\v1')
#17 /var/www/test_v3_current/test-pro-web/library/vendor/php-opencloud/openstack/src/OpenStack.php(157): OpenStack\Common\Service\Builder->createService('ObjectStore\\v1', Array)
#18 /var/www/test_v3_current/test-pro-web/application/test/cloudstorage/storagehelper.php(51): OpenStack\OpenStack->objectStoreV1()
#19 /var/www/test_v3_current/test-pro-web/application/modules/api/controllers/StoragetestController.php(50): application_test_cloudstorage_storagehelper->get_containers_list()
#20 /var/www/test_v3_current/test-pro-web/library/Zend/Controller/Action.php(516): Api_StoragetestController->getcontainerslistAction()
#21 /var/www/test_v3_current/test-pro-web/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('getcontainersli...')
#22 /var/www/test_v3_current/test-pro-web/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#23 /var/www/test_v3_current/test-pro-web/index.php(86): Zend_Controller_Front->dispatch()

**Comment by thatipelli69** [comment]
Hi @haphan , I have gone through with https://www.thatsgeeky.com/2016/08/openstack-php-and-ovh/. Here, it is stating that " when trying to use the default OpenStack constructor, the result was a 404 error against https://auth.cloud.ovh.net/v2.0/auth/tokens". So I updated the code as per this blog. But I don't know how things are working here now and how the code of official document is getting error (http://docs.os.php-opencloud.com/en/latest/services/object-store/v1/containers.html)

**Comment by haphan** [comment]
Can you post the curl response? Including request/response header and body @thatipelli69

**Comment by thatipelli69** [comment]
Request:
curl -X POST https://auth.cloud.ovh.net/v2.0/tokens -d '{"auth":{"passwordCredentials":{"username": "XXXXXXXXXX", "password":"XXXXXXXXX"}, "tenantId":"XXXXXXXXXXX"}}' -H 'Content-type: application/json'


Response:



Formatted JSON Data
{  
  "access":{  
    "token":{  
      "issued_at":"2017-10-13T14:04:58.925743",
      "expires":"2017-10-14T14:04:58Z",
      "id":"de0c059cb20a444694336275819cc969",
      "tenant":{  
        "description":"XXXXXXXXXXXXX",
        "enabled":true,
        "id":"XXXXXXXXXXXXXXXXX",
        "name":"XXXXXXXXXXXXXXXX"
      },
      "audit_ids":[  
        "XXXXXXXXXXXXXXXxx"
      ]
    },
    "serviceCatalog":[  
      {  
        "endpoints":[  
          {  
            "adminURL":"https://compute.bhs3.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15",
            "region":"BHS3",
            "internalURL":"https://compute.bhs3.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15",
            "id":"13d041e77e1b4074b0cbce0d8a824d37",
            "publicURL":"https://compute.bhs3.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15"
          },
          {  
            "adminURL":"https://compute.gra3.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15",
            "region":"GRA3",
            "internalURL":"https://compute.gra3.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15",
            "id":"5e4cebd91e2946ccb442c92b738653f2",
            "publicURL":"https://compute.gra3.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15"
          },
          {  
            "adminURL":"https://compute.waw1.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15",
            "region":"WAW1",
            "internalURL":"https://compute.waw1.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15",
            "id":"2d0a54efa03244e4a416054bf92e0f2f",
            "publicURL":"https://compute.waw1.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15"
          },
          {  
            "adminURL":"https://compute.sbg3.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15",
            "region":"SBG3",
            "internalURL":"https://compute.sbg3.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15",
            "id":"249ce50b948f4d8399feed677d34fd3e",
            "publicURL":"https://compute.sbg3.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15"
          },
          {  
            "adminURL":"https://compute.de1.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15",
            "region":"DE1",
            "internalURL":"https://compute.de1.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15",
            "id":"4600007ec2a045b3a40529cd34791ffa",
            "publicURL":"https://compute.de1.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15"
          }
        ],
        "endpoints_links":[  

        ],
        "type":"compute",
        "name":"nova"
      },
      {  
        "endpoints":[  
          {  
            "adminURL":"https://network.compute.bhs3.cloud.ovh.net/",
            "region":"BHS3",
            "internalURL":"https://network.compute.bhs3.cloud.ovh.net/",
            "id":"24c1bc0fe2f84d4e8810d9efe771e7cc",
            "publicURL":"https://network.compute.bhs3.cloud.ovh.net/"
          },
          {  
            "adminURL":"https://network.compute.gra3.cloud.ovh.net/",
            "region":"GRA3",
            "internalURL":"https://network.compute.gra3.cloud.ovh.net/",
            "id":"1f4c689f8a714c92a54bc97c34e28aef",
            "publicURL":"https://network.compute.gra3.cloud.ovh.net/"
          },
          {  
            "adminURL":"https://network.compute.waw1.cloud.ovh.net/",
            "region":"WAW1",
            "internalURL":"https://network.compute.waw1.cloud.ovh.net/",
            "id":"1736e066ec40430692670a2bb409d438",
            "publicURL":"https://network.compute.waw1.cloud.ovh.net/"
          },
          {  
            "adminURL":"https://network.compute.sbg3.cloud.ovh.net/",
            "region":"SBG3",
            "internalURL":"https://network.compute.sbg3.cloud.ovh.net/",
            "id":"685db393cd0d4d3781d4c3fda5b88a96",
            "publicURL":"https://network.compute.sbg3.cloud.ovh.net/"
          },
          {  
            "adminURL":"https://network.compute.de1.cloud.ovh.net/",
            "region":"DE1",
            "internalURL":"https://network.compute.de1.cloud.ovh.net/",
            "id":"6826ae22962446319d95f6b31c5be487",
            "publicURL":"https://network.compute.de1.cloud.ovh.net/"
          }
        ],
        "endpoints_links":[  

        ],
        "type":"network",
        "name":"neutron"
      },
      {  
        "endpoints":[  
          {  
            "adminURL":"https://volume.compute.bhs3.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15",
            "region":"BHS3",
            "internalURL":"https://volume.compute.bhs3.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15",
            "id":"3972eee7dcde4dad8259361aca1f87fb",
            "publicURL":"https://volume.compute.bhs3.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15"
          },
          {  
            "adminURL":"https://volume.compute.gra3.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15",
            "region":"GRA3",
            "internalURL":"https://volume.compute.gra3.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15",
            "id":"4b66981f8a374f848feb107284389c93",
            "publicURL":"https://volume.compute.gra3.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15"
          },
          {  
            "adminURL":"https://volume.compute.waw1.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15",
            "region":"WAW1",
            "internalURL":"https://volume.compute.waw1.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15",
            "id":"00fbb01d92b2469e81bc1272547cb805",
            "publicURL":"https://volume.compute.waw1.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15"
          },
          {  
            "adminURL":"https://volume.compute.sbg3.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15",
            "region":"SBG3",
            "internalURL":"https://volume.compute.sbg3.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15",
            "id":"adcb0661a8984ed8af112ca772b0b965",
            "publicURL":"https://volume.compute.sbg3.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15"
          },
          {  
            "adminURL":"https://volume.compute.de1.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15",
            "region":"DE1",
            "internalURL":"https://volume.compute.de1.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15",
            "id":"8c1100f929bf46f886d05b8f32c25b93",
            "publicURL":"https://volume.compute.de1.cloud.ovh.net/v2/49bcd7977d0c4844a095d644f7069d15"
          }
        ],
        "endpoints_links":[  

        ],
        "type":"volumev2",
        "name":"cinderv2"
      },
      {  
        "endpoints":[  
          {  
            "adminURL":"https://image.compute.bhs3.cloud.ovh.net/",
            "region":"BHS3",
            "internalURL":"https://image.compute.bhs3.cloud.ovh.net/",
            "id":"01253b0c991645a89c0485261b5b72b9",
            "publicURL":"https://image.compute.bhs3.cloud.ovh.net/"
          },
          {  
            "adminURL":"https://image.compute.gra3.cloud.ovh.net/",
            "region":"GRA3",
            "internalURL":"https://image.compute.gra3.cloud.ovh.net/",
            "id":"5ed6cdc03ccf434fb1fde62e85decc7e",
            "publicURL":"https://image.compute.gra3.cloud.ovh.net/"
          },
          {  
            "adminURL":"https://image.compute.waw1.cloud.ovh.net/",
            "region":"WAW1",
            "internalURL":"https://image.compute.waw1.cloud.ovh.net/",
            "id":"5d0a1886393a4a2ab0cb6d20a477e794",
            "publicURL":"https://image.compute.waw1.cloud.ovh.net/"
          },
          {  
            "adminURL":"https://image.compute.sbg3.cloud.ovh.net/",
            "region":"SBG3",
            "internalURL":"https://image.compute.sbg3.cloud.ovh.net/",
            "id":"17dd0e30b13b4a07831780adfe2544b3",
            "publicURL":"https://image.compute.sbg3.cloud.ovh.net/"
          },
          {  
            "adminURL":"https://image.compute.de1.cloud.ovh.net/",
            "region":"DE1",
            "internalURL":"https://image.compute.de1.cloud.ovh.net/",
            "id":"0a8c228bc1734884b6fcc090ab83ef37",
            "publicURL":"https://image.compute.de1.cloud.ovh.net/"
          }
        ],
        "endpoints_links":[  

        ],
        "type":"image",
        "name":"glance"
      },
      {  
        "endpoints":[  
          {  
            "adminURL":"https://volume.compute.bhs3.cloud.ovh.net/v1/49bcd7977d0c4844a095d644f7069d15",
            "region":"BHS3",
            "internalURL":"https://volume.compute.bhs3.cloud.ovh.net/v1/49bcd7977d0c4844a095d644f7069d15",
            "id":"0914e59707894620b24e62faee393074",
            "publicURL":"https://volume.compute.bhs3.cloud.ovh.net/v1/49bcd7977d0c4844a095d644f7069d15"
          },
          {  
            "adminURL":"https://volume.compute.gra3.cloud.ovh.net/v1/49bcd7977d0c4844a095d644f7069d15",
            "region":"GRA3",
            "internalURL":"https://volume.compute.gra3.cloud.ovh.net/v1/49bcd7977d0c4844a095d644f7069d15",
            "id":"513b1127590049af859ae5357d2d043e",
            "publicURL":"https://volume.compute.gra3.cloud.ovh.net/v1/49bcd7977d0c4844a095d644f7069d15"
          },
          {  
            "adminURL":"https://volume.compute.waw1.cloud.ovh.net/v1/49bcd7977d0c4844a095d644f7069d15",
            "region":"WAW1",
            "internalURL":"https://volume.compute.waw1.cloud.ovh.net/v1/49bcd7977d0c4844a095d644f7069d15",
            "id":"738e8d493217409ab6a8d0b67aba9e38",
            "publicURL":"https://volume.compute.waw1.cloud.ovh.net/v1/49bcd7977d0c4844a095d644f7069d15"
          },
          {  
            "adminURL":"https://volume.compute.sbg3.cloud.ovh.net/v1/49bcd7977d0c4844a095d644f7069d15",
            "region":"SBG3",
            "internalURL":"https://volume.compute.sbg3.cloud.ovh.net/v1/49bcd7977d0c4844a095d644f7069d15",
            "id":"04718b9d79054055be6a49a0cf82d46e",
            "publicURL":"https://volume.compute.sbg3.cloud.ovh.net/v1/49bcd7977d0c4844a095d644f7069d15"
          },
          {  
            "adminURL":"https://volume.compute.de1.cloud.ovh.net/v1/49bcd7977d0c4844a095d644f7069d15",
            "region":"DE1",
            "internalURL":"https://volume.compute.de1.cloud.ovh.net/v1/49bcd7977d0c4844a095d644f7069d15",
            "id":"6bf5ed80d8bd43e5b957b5f755379583",
            "publicURL":"https://volume.compute.de1.cloud.ovh.net/v1/49bcd7977d0c4844a095d644f7069d15"
          }
        ],
        "endpoints_links":[  

        ],
        "type":"volume",
        "name":"cinder"
      },
      {  
        "endpoints":[  
          {  
            "adminURL":"https://storage.bhs3.cloud.ovh.net:8888/",
            "region":"BHS3",
            "internalURL":"http://127.0.0.1:8888/v1/AUTH_49bcd7977d0c4844a095d644f7069d15",
            "id":"54460c0ed9c443e8abff23aa8fed5d65",
            "publicURL":"https://storage.bhs3.cloud.ovh.net/v1/AUTH_49bcd7977d0c4844a095d644f7069d15"
          },
          {  
            "adminURL":"https://storage.gra3.cloud.ovh.net:8888/",
            "region":"GRA3",
            "internalURL":"http://127.0.0.1:8888/v1/AUTH_49bcd7977d0c4844a095d644f7069d15",
            "id":"6cad60d3453c44429fa4bfc4789d84e9",
            "publicURL":"https://storage.gra3.cloud.ovh.net/v1/AUTH_49bcd7977d0c4844a095d644f7069d15"
          },
          {  
            "adminURL":"https://storage.waw1.cloud.ovh.net:8888/",
            "region":"WAW1",
            "internalURL":"http://127.0.0.1:8888/v1/AUTH_49bcd7977d0c4844a095d644f7069d15",
            "id":"3aecce47501d476dac26ff41143ddc01",
            "publicURL":"https://storage.waw1.cloud.ovh.net/v1/AUTH_49bcd7977d0c4844a095d644f7069d15"
          },
          {  
            "adminURL":"https://storage.sbg3.cloud.ovh.net:8888/",
            "region":"SBG3",
            "internalURL":"http://127.0.0.1:8888/v1/AUTH_49bcd7977d0c4844a095d644f7069d15",
            "id":"27dc827fa45842809e5ffc798c1db7be",
            "publicURL":"https://storage.sbg3.cloud.ovh.net/v1/AUTH_49bcd7977d0c4844a095d644f7069d15"
          },
          {  
            "adminURL":"https://storage.de1.cloud.ovh.net:8888/",
            "region":"DE1",
            "internalURL":"http://127.0.0.1:8888/v1/AUTH_49bcd7977d0c4844a095d644f7069d15",
            "id":"0d7e155dc4af474182b91b07966d6533",
            "publicURL":"https://storage.de1.cloud.ovh.net/v1/AUTH_49bcd7977d0c4844a095d644f7069d15"
          }
        ],
        "endpoints_links":[  

        ],
        "type":"object-store",
        "name":"swift"
      },
      {  
        "endpoints":[  
          {  
            "adminURL":"https://auth.cloud.ovh.net:35357/v2.0",
            "region":"BHS3",
            "internalURL":"http://127.0.0.1:5000/v2.0",
            "id":"49df446fd99a4a7986faf411343aca39",
            "publicURL":"https://auth.cloud.ovh.net/v2.0"
          },
          {  
            "adminURL":"https://auth.cloud.ovh.net:35357/v2.0",
            "region":"GRA3",
            "internalURL":"http://127.0.0.1:5000/v2.0",
            "id":"2d48aaedb0d340aa83238946d656b3ae",
            "publicURL":"https://auth.cloud.ovh.net/v2.0"
          },
          {  
            "adminURL":"https://auth.cloud.ovh.net:35357/v2.0",
            "region":"WAW1",
            "internalURL":"http://127.0.0.1:5000/v2.0",
            "id":"0d633045a18847068feeee1bda60a683",
            "publicURL":"https://auth.cloud.ovh.net/v2.0"
          },
          {  
            "adminURL":"https://auth.cloud.ovh.net:35357/v2.0",
            "region":"SBG3",
            "internalURL":"http://127.0.0.1:5000/v2.0",
            "id":"091f37b1d1a74ce4bea72742ebcb5b33",
            "publicURL":"https://auth.cloud.ovh.net/v2.0"
          },
          {  
            "adminURL":"https://auth.cloud.ovh.net:35357/",
            "region":"DE1",
            "internalURL":"http://127.0.0.1:5000/",
            "id":"3d3ccce61f8b4c4a9c9cb45781cf327f",
            "publicURL":"https://auth.cloud.ovh.net/"
          }
        ],
        "endpoints_links":[  

        ],
        "type":"identity",
        "name":"keystone"
      }
    ],
    "user":{  
      "username":"XXXXXXXXXXXX",
      "roles_links":[  ],
      "id":"XXXXXXXXXXXXXXXX",
      "roles":[  
        {  
          "name":"project_operator"
        }
      ],
      "name":"XXXXXXXX"
    },
    "metadata":{  
      "is_admin":0,
      "roles":[  
        "942a61c1931e494eb01c73b8cb9f445f"
      ]
    }
  }
}

**Comment by ivtod** [comment]
Hi @thatipelli69, have you been able to make it work?
I think the problem is that OVH still use Identity API V2, you may notice that in the config params they provide they use 'tenants' instead of 'projects' (in API v2.0 projects were known as tenants).
Following the instructions in the blog post you provided should let you authenticate correctly.

**Comment by haphan** [comment]
@thatipelli69  @ivtod 

identity v2 (which rackspace and OVH are using) authentication is slightly different from that of v3.0

I have added a doc page for that: http://php-openstack-sdk.readthedocs.io/en/identity-v2/services/identity/v2/authentication.html

**Comment by Mecanik** [comment]
@haphan - Your example/documentantion does not work anymore. I just tried multiple times to use it, and everytime I get:

`Caught exception: "identityService" must be specified and implement OpenStack\Common\Auth\IdentityService`

I am using latest version of php-opencloud.

**Comment by haphan** [comment]
@Mecanik Please specify what version of keystone you are using (v2/v3). For v2, make sure you are using [this ](https://github.com/php-opencloud/openstack/blob/master/samples/identity/v2/authentication.php)

Post your code snippet here as well.

**Comment by Mecanik** [comment]
Obviously I am using v2, since I have quoted your previous answer. I managed to fix this, I don't even know how really. I think the mistake was that I followed this first: http://php-openstack-sdk.readthedocs.io/en/identity-v2/services/identity/v2/authentication.html

**Comment by aibarra11** [comment]
how was this fixed? i'm running into the exact same set of issues.

**Comment by chadyred** [comment]
Same issue here !
