### ISSUE TITLE
Is it possible to use hardlink or symlink functionality?

### ISSUE THREAD

**Issue by kolyadin** [php-opencloud/openstack#183]
I want some sort of linking between files, like unix ln command.
I found this:
https://docs.openstack.org/swift/pike/object.html

> swift.obj.diskfile.relink_paths(target_path, new_target_path, check_existing=False)

> Hard-links a file located in target_path using the second path new_target_path. Creates intermediate directories if required.

Is it possible to do this via current library?

**Comment by haphan** [comment]
I don't think so. This library is only an SDK that wraps the public REST API.
