### ISSUE TITLE
Endpoint and Auth token

### ISSUE THREAD

**Issue by yaros98** [php-opencloud/openstack#186]
Hello,

I was using _rackspace/php-opencloud_ in my project and I would like to switch to _php-opencloud/openstack_ instead. However, I'm not sure how to replicate what I had with the previous package.

I **only** have an OVH endpoint and auth token and used to do this:

```
$credentials = ['endpoint' => '', 'token' => ''];

$objectStore = new \stdClass();
$objectStore->name = 'cloudFiles';
$objectStore->type = 'object-store';

$endpoint = new \stdClass();
$endpoint->publicURL = $credentials['endpoint'];
$endpoint->region = self::$region;

$objectStore->endpoints = [$endpoint];

$client = new OpenStack($credentials['endpoint'],[]);
$client->setCatalog([$objectStore]);
$client->importCredentials(['token' => $credentials['token']]);

return $client;
```

How would I go about it for this project? I supposed "AuthUrl" in the OpenStack construct was similar to my endpoint, but I don't know about the auth token.

Any help is welcome... I've never used OpenStack before.

**Comment by haphan** [comment]
Hi @yaros98, please refer to http://docs.os.php-opencloud.com/en/latest/services/identity/v3/tokens.html#cache-authentication-token
