### ISSUE TITLE
PHP 7.2 support

### ISSUE THREAD

**Issue by nicolasmure** [php-opencloud/openstack#192]
Hello :)

[PHP 7.2](http://php.net/releases/7_2_0.php) as introduced the [object typehint](https://wiki.php.net/rfc/object-typehint), so it became a reserved keyword an can no longer be used as a class name (see exemple https://3v4l.org/XmtsZ ).

Do you have any plans to rename the `OpenStack\ObjectStore\v1\Models\Object` class ?

Thank you :)

**Comment by nicolasmure** [comment]
Oh, I haven't noticed the open PRs for this issue, #184 seems to be the most advanced fix at the moment.

**Comment by haphan** [comment]
#184 will fix the issue with 7.2
