### ISSUE TITLE
I can't login OpenStack 

### ISSUE THREAD

**Issue by emresaracoglu** [php-opencloud/openstack#222]
Hi,

I have just installed OpenStack and can not connect with this code:

```
<?php
	require_once '/home/username/vendor/autoload.php';

	$openstack = new OpenStack\OpenStack([
		'authUrl' => 'http://192.168.1.165/compute/v2.1',
		'region' => 'nova',
		'user' => [
			'id' => '469d182717934829b66f17b23082b137',
			'password' => 'secret'
		],
		'scope' => ['project' => ['id' => 'daa01cda57012341844ebacfc8ed2e98']]
	]);
	$compute = $openstack->computeV2(['region' => 'nova']);
	$servers = $compute->listServers(true);
	var_dump(iterator_to_array($servers));
```

I getting this error:

> Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST http://192.168.1.165/compute/v2.1/auth/tokens` resulted in a `401 Unauthorized` response: {"error": {"message": "The request you have made requires authentication.", "code": 401, "title": "Unauthorized"}} in /home/username/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113 Stack trace: #0 /home/username/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 /home/username/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 /home/username/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 /home/username/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4 /home/username/vendor/guzzlehttp/promises/src/Prom in /home/username/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113

Where do I make mistakes?

**Comment by emresaracoglu** [comment]
If I can change this parameter: 

`'authUrl' => 'http://192.168.1.165/compute/v2.1',`
to
`'authUrl' => 'http://192.168.1.165/compute/v2.0',`

I get this error:

> Fatal error: Uncaught Error: Call to a member function getServiceUrl() on null in /home/username/vendor/php-opencloud/openstack/src/Identity/v3/Service.php:49 Stack trace: #0 /home/username/vendor/php-opencloud/openstack/src/Common/Service/Builder.php(96): OpenStack\Identity\v3\Service->authenticate(Array) #1 /home/username/vendor/php-opencloud/openstack/src/Common/Service/Builder.php(82): OpenStack\Common\Service\Builder->stockHttpClient(Array, 'Compute\\v2') #2 /home/username/vendor/php-opencloud/openstack/src/OpenStack.php(90): OpenStack\Common\Service\Builder->createService('Compute\\v2', Array) #3 /home/username/public_html/_SubDomains/Cloud/test1.php(16): OpenStack\OpenStack->computeV2(Array) #4 {main} thrown in /home/username/vendor/php-opencloud/openstack/src/Identity/v3/Service.php on line 49

**Comment by haphan** [comment]
@emresaracoglu For identity v2.0, please refer to https://php-openstack-sdk.readthedocs.io/en/latest/services/identity/v2/authentication.html

I would strong recommend using `v3` if possible.

**Comment by emresaracoglu** [comment]
Thank you but What's this 'tenantName'?
