### ISSUE TITLE
How to fixed the validateToken

### ISSUE THREAD

**Issue by neetdai** [php-opencloud/openstack#229]
I want to validate token,so i use OpenStack\Identity\v3\Service validateToken method. But the api is different to [doc](https://developer.openstack.org/api-ref/identity/v3/#check-token), because the params just send X-Subject-Token, not X-Auth-Token. How can I fixed it?

**Comment by neetdai** [comment]
![wt x gx9e e oxde27](https://user-images.githubusercontent.com/17525313/37379769-20c3618e-2770-11e8-8d90-0065b3bfc7fb.png)

**Comment by haphan** [comment]
Correct me if I am wrong, there are 2 fields being sent
- `X-Auth-Token`: is a valid administrative token and is needed to access the api server.
- `X-Subject-Token`: is the token you want to check for validity.

That means the sdk follows exactly what was described in the doc.

**Comment by neetdai** [comment]
Oh! I try to use 
![nrjkr y6fp 5 98st l w1](https://user-images.githubusercontent.com/17525313/37383288-be74dbbc-2782-11e8-809b-e858f3de7113.png)
is ok.

But, i save the token to database, and then i have children class extends OpenStack\Identity\v3\Service. When validate token from my database before authenticate.

![82b48 azvn h 3 5 f nm u](https://user-images.githubusercontent.com/17525313/37383542-3ef630c8-2784-11e8-8c78-9f3c716fea70.png)


Is it a wrong way i use? What is right way?

**Comment by haphan** [comment]
I believe what you are trying to do is to re-use auth token.

 If it is the case, please follow this doc https://php-openstack-sdk.readthedocs.io/en/latest/services/identity/v3/tokens.html#cache-authentication-token

**Comment by neetdai** [comment]
Thank you
