### ISSUE TITLE
How is the Endpoint->url generated?

### ISSUE THREAD

**Issue by ghforgaofeng** [php-opencloud/openstack#230]
hi;
I want to connect my own server,
But 'Endpoint->url' is bad.
How is the Endpoint->url generated?

thanks.

**Comment by haphan** [comment]
How bad? Please provide error logs or var_dump. 

Alternatively you can ask this kind of question in our slack channel. Get your invitation here https://launchpass.com/phpopencloud

**Comment by ghforgaofeng** [comment]
Sorry, Maybe I didn’t say it clearly,
 I want to set a custom url: POST /ver_x/{tenant_id}/servers_x，
How to modify ver_x.

thanks.

**Comment by haphan** [comment]
api version is handled by the SDK and you are not supposed to change it.

In what scenario you want to modify the version?

**Comment by ghforgaofeng** [comment]
Thank you. 
I understand what you mean. It was a problem with my previous ideas. Now I can specify the service I want to access because of the specific version and path.
The problem has been solved.
My English is very bad. These are all from Google's translation.
