### ISSUE TITLE
How to force delete a volume.

### ISSUE THREAD

**Issue by ghforgaofeng** [php-opencloud/openstack#233]
Hi,
I have a problem：
Message：Invalid volume: Volume status must be available or error or error_restoring or error_extending or error_rollbacking and must not be migrating, attached, belong to a consistency group or have snapshots or be a replicative volume, but current status is error_deleting.

thanks.

**Comment by haphan** [comment]
@ghforgaofeng This looks like an error in back-end volume service itself. I would recommend using the administrative account to delete. If the problem persists, best to look into error log in either the controller nodes or block storage controller nodes.
