### ISSUE TITLE
Whole library is messed up

### ISSUE THREAD

**Issue by Mecanik** [php-opencloud/openstack#240]
As the title says, no offense for the work input in this library - but it's messed up. 

Nothing documented properly, most of them do not work due to Guzzle older version for example, the "examples" are with v3 auth, and plenty more.

This is an amazing tool for those that want to interact with openstack, but unfortunately it's not there yet.

I had to "fish" around a lot of time to see how to access **containerExists()**, but apparently you cannot in the latest version. However you are using in: **createLargeObject()**.

31 people that contribute to this repository, and nobody has the required time and patience to make proper documentation and examples ?

Really disappointed, this is my personal feedback. I might go with Amazon, just because they have a ton of documentation and examples - and that's with everything.

**Comment by haphan** [comment]
> Nothing documented properly, most of them do not work due to Guzzle older version for example, the "examples" are with v3 auth, and plenty more.

You are welcome to open issue for each and every `do-not-work`. This SDK supports guzzle 6 (latest) and both v2/v3 auth. Help me understand how we can make it better. 

> This is an amazing tool for those that want to interact with openstack, but unfortunately it's not there yet.

A handful of production products use this SDK. Maybe they are investing in a wrong library and shall look else where.

> 31 people that contribute to this repository, and nobody has the required time and patience to make proper documentation and examples ?

I case you believe in giving back to the community after benefiting from it,  your contribution is always welcome. None of contributors here are making a living out of this.

**Comment by haphan** [comment]
Now back to your question.


> Check if container exists ( function there, but how to use it ? )

```php
/** @var \OpenStack\ObjectStore\v1\Service $service */
$service = $openstack->objectStoreV1();

if (!$service->containerExists($segmentContainer)) { 
// do something here
}

```
> Get upload progress on large files from stream ( Did not see any documentation on this, nor any examples with the latest version )

I have not looked in to any solution supported by openstack/swift api  itself, but with Guzzle you can always define a callback for upload and download progress.

see http://docs.guzzlephp.org/en/stable/request-options.html#progress

```php 
$requestOptions = [
    'progress' => function(
            $downloadTotal,
            $downloadedBytes,
            $uploadTotal,
            $uploadedBytes
        ) {
            //do something
        }
];

$openstack = new OpenStack\OpenStack([
// ...
'requestOptions'   => $requestOptions
// ...
]);

```
 Hope this helps @Mecanik

**Comment by Mecanik** [comment]
> You are welcome to open issue for each and every do-not-work. This SDK supports guzzle 6 (latest) and both v2/v3 auth. Help me understand how we can make it better.

Sure, if I decide to go with this for my next project I will gladly help.

> A handful of production products use this SDK. Maybe they are investing in a wrong library and shall look else where.

I doubt that someone would use this for production, and even if they did... I won't go into this now.

> In case you believe in giving back to the community after benefiting from it, your contribution is always welcome. None of contributors here are making a living out of this.

Again, if I decided I can use this SDK for my next project I will contribute a lot.

My question now:

I'm not sure how this works:

```
/** @var \OpenStack\ObjectStore\v1\Service $service */
$service = $openstack->objectStoreV1();

if (!$service->containerExists($name)) { 
// do something here
}
```

As my IDE is unable to show this function linked to objectStoreV1(), so if it does work ( need to test now ) then it should have relation with objectStoreV1(). My IDE ( any IDE ) will show you where functions are coming from, how they relate, etc, however I repeat this containerExists() and other functions do not show up anywhere.

As for the progress, I`m 90% sure that you cannot get real progress from openstack ( at least now ) however I`m aware of Guzzle having this. 

Where did you find this?:

```
$requestOptions = [
    'progress' => function(
            $downloadTotal,
            $downloadedBytes,
            $uploadTotal,
            $uploadedBytes
        ) {
            //do something
        }
];

$openstack = new OpenStack\OpenStack([
// ...
'requestOptions'   => $requestOptions
// ...
]);
```

Haven't tested it yet, but thanks - looks promising for my goal!

One more small question, from what I see Guzzle can resume http requests, so could we (is there already?) a "resume" function if the upload of a large file times out ?

Thanks for everything @haphan

**Comment by Mecanik** [comment]
My bad, I just saw you found the progress on http://docs.guzzlephp.org/en/stable/request-options.html#progress ( still sleepy today ).

**Comment by Mecanik** [comment]
@haphan It seems that using this example:

```
$requestOptions = [
    'progress' => function(
            $downloadTotal,
            $downloadedBytes,
            $uploadTotal,
            $uploadedBytes
        ) {
            //do something
        }
];

$openstack = new OpenStack\OpenStack([
// ...
'requestOptions'   => $requestOptions
// ...
]);
```
Does not return anything but 0, maybe this should be somehow else implemented.

**Comment by Mecanik** [comment]
Progress currently works only with createObject, with createLargeObject the progress is always 0.
