### ISSUE TITLE
Removing sami/sami as composer dependency

### ISSUE THREAD

**Issue by haphan** [php-opencloud/openstack#252]
`Sami/sami` should not be required as a composer dependency and I plan to remove this.

@laszlof Are you owning the phpdoc site http://refdocs.os.php-opencloud.com/?

**Comment by haphan** [comment]
I am tagging @clwells as well since I know Nexcess is sponsoring the hosting of the documentation.

**Comment by laszlof** [comment]
@haphan Yeah. I have control over the hosting. Let me know what you need me to do :)

**Comment by haphan** [comment]
@laszlof  `vendor/bin/sami.php is ` will no longer be available. That means you need to install sami independently.

**Comment by laszlof** [comment]
@haphan this has been completed. Just tested and everything seems to be working.

**Comment by haphan** [comment]
thanks @laszlof. I will proceed to merge the change to master
