### ISSUE TITLE
Create Objects

### ISSUE THREAD

**Issue by alewitt** [php-opencloud/openstack#26]
[Docs](http://php-opencloudopenstack.readthedocs.org/en/latest/services/object-store/v1/objects.html) lack description on how to create and add objects to object storage

**Comment by karnajani** [comment]
Does this file outline the process? 

https://github.com/php-opencloud/openstack/blob/master/samples/object_store/v1/objects/create.php

If so, I'd be happy to do a PR

**Comment by alewitt** [comment]
I believe it does, Thanks!  please go ahead and pull request.
