### ISSUE TITLE
Is it possible to get  the storage url for objects?

### ISSUE THREAD

**Issue by alewitt** [php-opencloud/openstack#27]
Currently i can't find a way to get the storage url from this php client. I know how to get it using swift cli, but i can't figure out how to get it here.

in swift cli i can do
```
swift --info --os-auth-url https://identity.open.softlayer.com/v3 --auth-version 3 --os-region 'dallas' --os-project-id kjdjkasdhkjh28h28hodasdasd --os-user-id kajsdfhkajhfkjaf2i7y9882dsaj --os-password 'jkhasdASKJH28-1d' stat -v
```
and that will return
```
StorageURL: https://dal.objectstorage.open.softlayer.com/v1/AUTH_kjdjkasdhkjh28h28hodasdasd
                     Auth Token: <my auth token>
                        Account: AUTH_kjdjkasdhkjh28h28hodasdasd
                     Containers: 1
                        Objects: 12
                          Bytes: 4301436
Containers in policy "standard": 1
   Objects in policy "standard": 12
     Bytes in policy "standard": 4301436
                     X-Trans-Id: <my trans id>
    X-Account-Project-Domain-Id: <account project domain id>
                    X-Timestamp: 1447705889.39341
                   Content-Type: text/plain; charset=utf-8
                  Accept-Ranges: bytes
```

**Comment by jamiehannaford** [comment]
@alewitt Not currently, but I'll look into this (and the Swift docs) tomorrow

**Comment by alewitt** [comment]
i did notice [this method](https://github.com/php-opencloud/openstack/blob/master/src/Identity/v3/Service.php#L23-L30), is that somethig that would help me here?

**Comment by jamiehannaford** [comment]
@alewitt I've just added a new method. Does this work for you?

```php
$object->getPublicUri();
```

**Comment by alewitt** [comment]
Thanks! let me check.

**Comment by alewitt** [comment]
@jamiehannaford Thanks again for putting that in, unfortunately its not exactly what we are looking for.

That gave me the base url of my webpage www.wordpress-instance.net/wp-content/uploads/file.png
but i need the actual endpoint for object storage. ex for our object storage in dallas `https://dal.objectstorage.open.softlayer.com/v1/AUTH_<projectId>`

**Comment by jamiehannaford** [comment]
@alewitt Okay, if it's the actual Swift base URL endpoint you need, you can change the visibility of [`getHttpBaseUrl`](https://github.com/php-opencloud/openstack/blob/master/src/Common/Api/Operator.php#L126) from `protected` to `public`. Why do you need the URL in the first place?

**Comment by alewitt** [comment]
@jamiehannaford In order for us to retrieve the images from object storage and view them on our webpage we label the OS container's ACL as `.r:*` then use the base url to point the the object as if it was a static web image.

**Comment by alewitt** [comment]
@jamiehannaford for example
`$url = 'https://dal.objectstorage.open.softlayer.com/v1/AUTH_' . $projectId . '/' . $container . '/' . $object;`
that is the hardcoded url that points to my object storage and returns the image that my site is able to load. Note the container has aldready been marked as public `.r:*`

**Comment by alewitt** [comment]
if the method `$object->getPublicUri();` returns that whole url to me, than thats all i need

**Comment by alewitt** [comment]
@jamiehannaford My gut tells me your method is doing what i want.
I am just having a hard time testing it. right now im getting this error `PHP Fatal error:  Call to undefined method OpenStack\\ObjectStore\\v1\\Models\\Object::getPublicUri()`

This is how im trying  to call it 
```
$objectUrl = $openstack->objectStoreV1()
                    ->getContainer($container)
                    ->getObject($object)
                    ->getPublicUri();
```

**Comment by jamiehannaford** [comment]
@alewitt Are you using `dev-master` as the version? Try running `composer update --prefer-source`

**Comment by alewitt** [comment]
@jamiehannaford i have this in my composer.json
```
    "repositories": [
       {
          "type": "vcs",
          "url": "git@github.com:php-opencloud/openstack.git"
        }
    ],
    "license": "GPLv3",
    "require": {
                "php-opencloud/openstack": "dev-master"
        }
```

**Comment by notFloran** [comment]
For [packagist](https://packagist.org/packages/php-opencloud/openstack), the last commit is https://github.com/php-opencloud/openstack/commit/cb07620603efee6a5146aefb96f6e6f46a8c5052 instead of https://github.com/php-opencloud/openstack/commit/9715be70f0603358b2230a9103c20c526e82a9a8

Perhaps a problem with the webhook that updates packagist.

Until the problem is corrected, you can force Composer to get the last commit with:
```
"php-opencloud/openstack": "dev-master#9715be7"
``

**Comment by alewitt** [comment]
thanks

**Comment by alewitt** [comment]
@jamiehannaford can you please go to packagist and update it so that it is using the latest commit? @notFloran is right, its way behind on the commit tree.

**Comment by alewitt** [comment]
i discover that if you want to specify the use of a git repo over packagist, you have to specify the repository tag in your projects root composer.json.

**Comment by alewitt** [comment]
@jamiehannaford I got most of my issues sorted out, but im still on the mission to get this to work. I still havent been able to test if the method is correct because i haven't gotten it to run yet. This is the error im getting now.
```
PHP Catchable fatal error:  Argument 1 passed to OpenStack\\Common\\Transport\\Utils::addPaths() must implement interface Psr\\Http\\Message\\UriInterface, null given, called in /home/vcap/app/htdocs/vendor/php-opencloud/openstack/src/ObjectStore/v1/Models/Object.php on line 67 and defined in /home/vcap/app/htdocs/vendor/php-opencloud/openstack/src/Common/Transport/Utils.php on line 73
```

**Comment by alewitt** [comment]
@jamiehannaford So i forked your repo just to workaround that error and see if im getting the correct url from your method. This is how i changed the method:
```
public function getPublicUri()
    {
        return (string)$this->getHttpBaseUrl() . '/' . $this->containerName . '/' . $this->name;
    }
```
Unfortunately this is giving me the wrong url. The url im seeing is `/WordPress/wp-content/uploads/2015/11/a2d5/BlueHacksCostaRicaFB.png`; in generic terms that is `/container/object`; this makes it look like `$this->getHttpBaseUrl()` is returning nothing. So maybe i did something wrong in my fork, but to me it seems something is getting lost in the `$this->getHttpBaseUrl()` call.

Any thoughts @jamiehannaford?

**Comment by jamiehannaford** [comment]
@alewitt There's no point casting it to a string, since you're just silencing the original error. For some reason, the base URL is not being retrieved (or set) from the Guzzle HTTP client. Did you modify `getHttpBaseUrl` at all? It shouldn't return `null`. 

The only other potential problem could be that it's not retrieving the URL from your catalog, but I'm not sure that's the problem because an error would have been thrown much earlier.

**Comment by alewitt** [comment]
@jamiehannaford i only edited the getPublicUrl() method, i didn't touch getHttpBaseUrl. It seems that it is failing to retrieve the url from the catalog, which is odd because it must be getting the url at some point in order to be able to create and destroy objects and containers.

**Comment by jamiehannaford** [comment]
@alewitt I'll take a look at this now. BTW I've just redacted all your passwords, usernames and tenant IDs from your code samples - please make sure not to post them online :)

**Comment by alewitt** [comment]
@jamiehannaford thank you for taking a look. i am aware i posted them. they are not important to me, and unnecessary to be kept hidden. there is no confidential info behind them. thanks though, i'll remove them in the future!

**Comment by jamiehannaford** [comment]
@alewitt found the problem: can you change [this line](https://github.com/php-opencloud/openstack/blob/master/src/Common/Api/Operator.php#L128) to `base_uri`. I'll push the change after I've finished refactoring something else.

**Comment by alewitt** [comment]
@jamiehannaford MY SAVIOR!!! Thanks so much for taking the time to help me through this long thread.. that did it!
