### ISSUE TITLE
The body of an object is fetched by default

### ISSUE THREAD

**Issue by chapa** [php-opencloud/openstack#292]
Contrary to what's written in the [phpdoc of the method](https://github.com/php-opencloud/openstack/blob/3eba351cd04cf73a54984334e5da2fe4cf6efe1a/src/ObjectStore/v1/Models/StorageObject.php#L140-L141), calling `StorageObject::download()` will fetch the whole file before returning it (as a `StreamInterface`, indeed).

I don't know if it has always been the case, maybe it's a change on the Guzzle side, but now the whole file is fetched. It becomes a problem with large files because we can't start processing them (e.g. returning them to client) before they've been completely downloaded.

I found that using the [`'stream'`](http://docs.guzzlephp.org/en/stable/request-options.html#stream-option) option from Guzzle solve the issue, but it's not as simple as that...

By adding this option in the `'requestOptions'` option of `OpenStack`, it will brake the authentication request that doesn't seems to support streams. The `Utils::jsonDecode($response)` will return an empty string, so `Utils::jsonDecode($response)['access']['token']` will fail :
https://github.com/php-opencloud/openstack/blob/3eba351cd04cf73a54984334e5da2fe4cf6efe1a/src/Identity/v2/Models/Token.php#L46

The problem seems to be here, where the body of the response is casted to a string instead of properly handled :
https://github.com/php-opencloud/openstack/blob/3eba351cd04cf73a54984334e5da2fe4cf6efe1a/src/Common/Transport/Utils.php#L23

But it's not as simple as changing `(string) $response->getBody()` by `$response->getBody()->getContents()`, because the stream returned by Guzzle is not seekable (when you set the `'stream'` option to `true`). `Utils::jsonDecode($response)` is called more than one with the same `$response`, so the second time it also returns an empty string (I guess because the content of the stream has been consumed during the first call).

I managed to get around it with a dirty solution consisting of having two `OpenStack` objects : one with `'requestOptions' => ['stream' => true]` and the other without. I can then do something like this :
```php
$openstack = new OpenStack([
    // ...
]);

$streamedOpenstack = new OpenStack([
    // ...
    'requestOptions' => [
        'stream' => true,
    ],
]);

$objectStore = $streamedOpenstack->objectStoreV1([
    // Give the identity service from the non streamed OpenStack
    //  so it doesn't stream requests for authentication
    'identityService' => $openstack->identityV2(),
]);
```

Here is a small repository so you can test what I'm saying : https://github.com/chapa/php-opencloud-openstack-stream

I think the problem could be solved in several ways  :
1. The `'stream'` option of Guzzle could be set to `true` in `ObjectStore::download()` so it doesn't affect other requests.
2. Errors of handling non seekable streams could be fixed when the user provides `'requestOptions' => ['stream' => true]` to the `OpenStack` constructor.
3. Guzzle options could be taken into account by `ObjectStore::download()`. And more generally by any method that use `OperatorTrait::sendRequest()`. Currently we have to use the `OpenStack` constructor `'requestOptions'` option if we want to customize Guzzle options, we can't give options to Guzzle on specific operations. If we do `$object->download(['requestOptions' => ['stream' => true]])` it doesn't work (request options are not forwarded to the Guzzle `Client`), because `RequestSerializer::serializeOptions()` called in `OperatorTrait::sendRequest()` [removes it](https://github.com/php-opencloud/openstack/blob/3eba351cd04cf73a54984334e5da2fe4cf6efe1a/src/Common/Api/OperatorTrait.php#L114).

**Comment by haphan** [comment]
@chapa You get it right totally. By default, guzzle instance is shared across streaming and non-streaming API calls. 

At the moment, as you figured out, users only have the option to create 2 OpenStack instances with stream enabled request options.

I'm open to pull request to solve this problem.
