### ISSUE TITLE
Unable To Fetch Error Code

### ISSUE THREAD

**Issue by FaruquiSahab** [php-opencloud/openstack#293]
How can I fetch response error code for every call
I'm unable to do this all properties are marked as private
Example:

```
$instance = $this->computeV2->getServer(['id' => '{id}']);
$volumeAttachment = $instance->attachVolume('{id}');
```
Unable to get exact error code for any call

**Comment by haphan** [comment]
How would you like to retrieve the error code? 

I don't have access to OpenStack atm, but I recall you can catch `OpenStack\Common\Error\BadResponseError`

**Comment by FaruquiSahab** [comment]
you mean to say like this
try{ 
      ....
} catch (OpenStack\Common\Error\BadResponseError $ex){
     ???
}

**Comment by haphan** [comment]
Yes. Does it work for you?

**Comment by FaruquiSahab** [comment]
Yes this works
```
catch(\OpenStack\Common\Error\BadResponseError $BadResponseError){

                $errorCode = $BadResponseError->getResponse()->getStatusCode();
                return $errorCode;
}
```
