### ISSUE TITLE
Empty Object When Fetching Single Record

### ISSUE THREAD

**Issue by FaruquiSahab** [php-opencloud/openstack#294]
Empty object when fetching single record
Not only the provided example but all other like volume, flavor, server, template, snapshot etc are null OR empty when try to get by id
Here's the code snippet:
```
$this->openstack = new \OpenStack\OpenStack([
            'authUrl' => 'ip:port/v3',
            'user' => [
                'name'      => '{{username}}',
                'domain'    => [
                    'name'  => 'default'
                ],
                'password'  => '{{password}}'
            ],
            'region' => '{{region}}',
        ]);
$this->identityV3       = $this->openstack->identityV3();
$project = $this->identityV3->getProject('cada158b46134c80a8e1dac2d1467578');
```

**Comment by haphan** [comment]
You must call `$project->retrieve()` to populate the response.

Ref https://php-openstack-sdk.readthedocs.io/en/latest/services/identity/v3/projects.html#show-project-details

**Comment by FaruquiSahab** [comment]
this is the response i get after the hit:
`object(OpenStack\Identity\v3\Models\Project)#43 (11) { ["domainId"]=> NULL ["parentId"]=> NULL ["enabled"]=> NULL ["description"]=> NULL ["id"]=> string(32) "44be6fc2fdee44228ec4133451de4b50" ["links"]=> NULL ["name"]=> NULL ["aliases"]=> array(2) { ["domain_id"]=> string(8) "domainId" ["parent_id"]=> string(8) "parentId" } ["resourceKey"]=> string(7) "project" ["resourcesKey"]=> string(8) "projects" ["markerKey"]=> NULL } `
and when get after ->retrieve() it gives NULL
