### ISSUE TITLE
Empty object all properties are null when fetching single record

### ISSUE THREAD

**Issue by FaruquiSahab** [php-opencloud/openstack#295]
Empty object when fetching single record
Not only the provided example but all other like volume, flavor, server, template, snapshot etc are null OR empty when try to get by id
Here's the code snippet:

```
$project = $this->identityV3->getProject('44be6fc2fdee44228ec4133451de4b50');
$project->retrieve();
```
When I var_dump($project)
result is:
`object(OpenStack\Identity\v3\Models\Project)#43 (11) { ["domainId"]=> NULL ["parentId"]=> NULL ["enabled"]=> NULL ["description"]=> NULL ["id"]=> string(32) "44be6fc2fdee44228ec4133451de4b50" ["links"]=> NULL ["name"]=> NULL ["aliases"]=> array(2) { ["domain_id"]=> string(8) "domainId" ["parent_id"]=> string(8) "parentId" } ["resourceKey"]=> string(7) "project" ["resourcesKey"]=> string(8) "projects" ["markerKey"]=> NULL }`
and when i var_dump($project->retrieve());
result is NULL

**Comment by FaruquiSahab** [comment]
![image](https://user-images.githubusercontent.com/44661979/71880023-39cbf000-3151-11ea-84c9-0a68951646bf.png)
.......
The Project is valid project and exist and user is also assign with proper roles...
List Roles command is working fine but when fetching single record it doesn't return the details

**Comment by FaruquiSahab** [comment]
```
$this->openstack = new \OpenStack\OpenStack([
            'authUrl'   =>  'xxx.xx.x.xxx:5000/v3',
            'user'      => [
                'name'      => 'my-username',
                'domain'    => [
                    'name'  => 'Default'
                ],
                'password'  => 'my-password'
            ]
        ]);
        $this->identityV3       = $this->openstack->identityV3(['region' => 'RegionOne']);
        $this->computeV2        = $this->openstack->computeV2(['region' => 'RegionOne']);
        $this->blockStorageV2   = $this->openstack->blockStorageV2(['region' => 'RegionOne']);
        $this->imagesV2         = $this->openstack->imagesV2(['region' => 'RegionOne']);
        $this->networkingV2     = $this->openstack->networkingV2(['region' => 'RegionOne']);
        $this->objectStoreV1    = $this->openstack->objectStoreV1(['region' => 'RegionOne']);
```

**Comment by haphan** [comment]
Hi @FaruquiSahab, `retrieve()` issues a call to the OpenStack API and populates response to itself.

```php
$project->retrieve();
var_dump($project);
```

**Comment by FaruquiSahab** [comment]
Oh I'm extremely sorry for inconvenience 
Thanks Man :)
