### ISSUE TITLE
Convert v2.0 to v3.0

### ISSUE THREAD

**Issue by brunopaiva15** [php-opencloud/openstack#297]
Hi.

I have this code for OpenStack Swift v2.0. I want to convert it to v3.0.

Can someone help me please ???

			// OVH cloud authentication information
            $authUrl = 'https://auth.cloud.ovh.net/v2.0';  // Access point to the Identity service defines in the "Access and security" part then in the "API access" tab.
            $username = '[USERNAME]'; // Horizon user
            $password_horizon = '[PASSWORD]'; // Horizon password
            $tenant = '[OS_TENANT_NAME]'; // OS_TENANT_NAME of the OpenStack RC file
            // Swift informations 
            $swiftUrl = 'https://storage.uk1.cloud.ovh.net/v1/AUTH_[API]'; // Access point to the Object Store service defines in the "Access and security" part then in the "API access" tah.
            $serviceName = 'swift';
            $region = 'UK1';

            // Intitialization of the constructor
            $client = new OpenStack($authUrl, array(
                'username' => $username,
                'password' => $password_horizon,
                'tenantName' => $tenant
                    )
            );

            // Calling up the authentication function
            $client->authenticate();

            // Retrieving the object store
            $service = $client->objectStoreService($serviceName, $region);

            // Retrieving the object container
            $container = $service->getContainer('storage_hiberfile');

**Comment by Ydalb** [comment]
any news about this @brunopaiva15 ?

**Comment by chapa** [comment]
Hello,

I used to build the client like this in v2 :
```php
$client = new OpenStack([
    'authUrl' => $this->authUrl,
    'region' => $this->region,
    'username' => $this->username,
    'password' => $this->password,
    'tenantId' => $this->tenantId,
]);
```

Now I build it like this :
```php
$client = new OpenStack([
    'authUrl' => $this->authUrl,
    'region' => $this->region,
    'user' => [
        'name' => $this->username,
        'password' => $this->password,
        'domain' => ['id' => 'default'],
    ],
    'scope' => [
        'project' => [
            'id' => $this->tenantId,
        ],
    ],
]);
```

I use tenant id instead of tenant name, but maybe this request example could help you if you need to use tenant name : https://storage.p19.cloud.ovh.net/v1/AUTH_47f7eb0153a7447799377451f59357ce/public/keystone-v3-request.txt
(taken from http://travaux.ovh.net/?do=details&id=42179&#comment50168)

**Comment by haphan** [comment]
@chapa already provided a good example.

The tenant name and ID can be found from RC file downloading from OVH Cloud Control Panel or the OpenStack Horizon. 

For authentication, since Identity V3 is a multi-tenanted environment, you must either pass a `scope.project.id` or  `scope.project.name` and `scope.project.domain`

**Comment by brunopaiva15** [comment]
> Hello,
> 
> I used to build the client like this in v2 :
> 
> ```
> $client = new OpenStack([
>     'authUrl' => $this->authUrl,
>     'region' => $this->region,
>     'username' => $this->username,
>     'password' => $this->password,
>     'tenantId' => $this->tenantId,
> ]);
> ```
> 
> Now I build it like this :
> 
> ```
> $client = new OpenStack([
>     'authUrl' => $this->authUrl,
>     'region' => $this->region,
>     'user' => [
>         'name' => $this->username,
>         'password' => $this->password,
>         'domain' => ['id' => 'default'],
>     ],
>     'scope' => [
>         'project' => [
>             'id' => $this->tenantId,
>         ],
>     ],
> ]);
> ```
> 
> I use tenant id instead of tenant name, but maybe this request example could help you if you need to use tenant name : https://storage.p19.cloud.ovh.net/v1/AUTH_47f7eb0153a7447799377451f59357ce/public/keystone-v3-request.txt
> (taken from http://travaux.ovh.net/?do=details&id=42179&#comment50168)

Oh my god, thank you so much.

**Comment by brunopaiva15** [comment]
I close the issue.
