### ISSUE TITLE
not getting install by composer

### ISSUE THREAD

**Issue by amarvora** [php-opencloud/openstack#307]
I am getting below error while installing from composer

The "http://repo.packagist.org/p/provider-2020-04%2448896012ebea9f4d2d78be73534c5de5b269f34b243a839ec69309c054a1537e.json" file could not be downloaded: failed to open stream: Network is unreachable
http://repo.packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date

  [Composer\Downloader\TransportException]
  The "http://repo.packagist.org/p/php-opencloud/openstack%248a9341edb64767b5d8414d1038ff6911293dcb5fd3b4b650ec531416b93f1916.json" file could not be downloaded: failed to open stream: Network is unreacha
  ble

**Comment by haphan** [comment]
Packagist seems down today :)
