### ISSUE TITLE
Class 'Symfony\Component\EventDispatcher\Event' not found 

### ISSUE THREAD

**Issue by ap-coder** [php-opencloud/openstack#314]
Any fixes for this package concerning guzzlehttp?

**Comment by alcalyn** [comment]
I made this one recently: https://github.com/php-opencloud/openstack/pull/331 but it does not fixes the error you are describing.

I get your error, but I fixed it by using updated version of openstack/flysystem/symfony (I cannot say which one caused this bug)

**Comment by k0ka** [comment]
We do test now the library with both the highest and the lowest possible dependencies. So  I guess the problem is gone. If it still persist please show what versions of dependencies are you using.
