### ISSUE TITLE
Php 8 support

### ISSUE THREAD

**Issue by hedii** [php-opencloud/openstack#322]
Hi, it looks like the latest php release (8.0) is not supported.
Every dependency listed in composer.json has an available version compatible with php 8.0.
But the test suite may need some updates using a newer phpunit version.

**Comment by ChristophWurst** [comment]
FYI it's all there in https://github.com/php-opencloud/openstack/pull/325. From what I can tell the package will just work fine with php8.0 as is, but I'd still hope the maintainers have a moment to review that PR soon-ish :)

:v:

**Comment by haphan** [comment]
😅 let me try to review and merge.

Been very with my 9 to 5 lately.

**Comment by ChristophWurst** [comment]
No worries @haphan and sorry if I was too pushy.

**Comment by pcieszkowski** [comment]
Any progress on this? :)

**Comment by ChristophWurst** [comment]
@pcieszkowski you may help test https://github.com/php-opencloud/openstack/pull/325. From what I can tell this package works fine with php8 but having it double-checked won't hurt.

**Comment by pcieszkowski** [comment]
@ChristophWurst  I'll give it a try later on

**Comment by pcieszkowski** [comment]
@ChristophWurst glad to tell that it works! smooth as butter :)

**Comment by hedii** [comment]
Fixed by release [3.2.0](https://github.com/php-opencloud/openstack/releases/tag/v3.2.0)

Thanks
