### ISSUE TITLE
The remote server returned a "401 UNAUTHORIZED" error for the following transaction: Request 

### ISSUE THREAD

**Issue by jjj117** [php-opencloud/openstack#329]
OpenStack\Common\Error\BadResponseError
HTTP Error ~~~~~~~~~~ The remote server returned a "401 UNAUTHORIZED" error for the following transaction: Request ~~~~~~~ POST /v3/auth/tokens HTTP/1.1 User-Agent: GuzzleHttp/7 Content-Type: application/json Host: 192.168.2.11:5000 Response ~~~~~~~~ HTTP/1.1 401 UNAUTHORIZED Date: Fri, 26 Mar 2021 07:31:11 GMT Server: Apache/2.4.41 (Ubuntu) WWW-Authenticate: Keystone uri="http://192.168.2.11:5000/v3" Content-Length: 109 Vary: X-Auth-Token x-openstack-request-id: req-f7192d5b-eebf-452a-b1ac-ae9abd20bbe5 Content-Type: application/json {"error":{"code":401,"message":"The request you have made requires authentication.","title":"Unauthorized"}} Further information ~~~~~~~~~~~~~~~~~~~ Please ensure that your authentication credentials are valid. Visit http://docs.php-opencloud.com/en/latest/http-codes for more information about debugging HTTP status codes, or file a support issue on https://github.com/php-opencloud/openstack/issues.

```
$openstack = new OpenStack([
            'authUrl' => 'http://192.168.2.11:5000/v3',
            'region' => 'default',
            'user' => [
                'id' => 'admin',
                'password' => 'ADMIN_PASS',
                'domain' => ['id' => 'default']
            ]
        ]);

        $service = $openstack->imagesV2();

        $service->getImage('aa80fd65-1350-4b77-80d5-7d1e8b7d597d');
```

**Comment by jjj117** [comment]
chanage id to name ,like this :
```$openstack = new OpenStack([
            'authUrl' => 'http://192.168.2.11:5000/v3',
            'region' => 'default',
            'user' => [
                'name' => 'admin',
                'password' => 'ADMIN_PASS',
                'domain' => ['name' => 'default']
            ]
        ]);```

**Comment by divyeshccl** [comment]
I'm facing the same issue

**Comment by k0ka** [comment]
It means credentials are wrong. Are you able to authorize via cli tool using them?

**Comment by divyeshccl** [comment]
Thank you @k0ka.

I resolved it. I'm using wrong username.
