### ISSUE TITLE
Call to undefined function GuzzleHttp\Psr7\modify_request()

### ISSUE THREAD

**Issue by andrecolza** [php-opencloud/openstack#333]
The function modify_request was deprecated in GuzzleHttp\Psr7 2.0.0, it should be replaced with Utils::modifyRequest introduced in 1.7.0 to prevent this error.

**Comment by andrecolza** [comment]
#332

**Comment by k0ka** [comment]
fixed in https://github.com/php-opencloud/openstack/pull/331
