### ISSUE TITLE
Feature Request - Add app credentials 

### ISSUE THREAD

**Issue by smarcet** [php-opencloud/openstack#337]
hello guys , greetings !!!  i work for the OSF i do think this feature will be really useful matter of fact we are using this lib to integration openstackid.org with swift object storage using app credentials
https://docs.openstack.org/keystone/latest/user/application_credentials.html
here is the PR #336 

regards

**Comment by k0ka** [comment]
Released in https://github.com/php-opencloud/openstack/releases/tag/v3.5.0
