### ISSUE TITLE
PHP Error in file src/Compute/v2/Api.php 

### ISSUE THREAD

**Issue by EoleDev** [php-opencloud/openstack#34]
Hello,
excuse me for my not very good english :)
I think there is a mistake in the lines 191 of the file src/Compute/v2/Api.php.

The code is : $definition['path'] += '/detail';
maybe, to concatenate two chains it would be : $definition['path'] .= '/detail';

i hope i haven't made myself a mistake, and i want to say thank you for your great job!

**Comment by jamiehannaford** [comment]
@EoleDev Great catch, thanks for posting!
