### ISSUE TITLE
question: can we suspend and un-suspend server?

### ISSUE THREAD

**Issue by mshannaq** [php-opencloud/openstack#393]
Hello

openstack cmd support suspend/resume server using `openstack server suspend` and `openstack server resume`

can I simulate this command using `php-opencloud/openstack` or does the suspend and resume command available because I have check the documentation and I did not find how to suspend and resume server.

Thanks a lot

**Comment by k0ka** [comment]
Hello

The sdk didn't support ssupend/resume server until now. 
I released it just now in https://github.com/php-opencloud/openstack/releases/tag/v3.7.0

https://php-openstack-sdk.readthedocs.io/en/latest/services/compute/v2/servers.html#suspend
