### ISSUE TITLE
getVolumesAttached to server

### ISSUE THREAD

**Issue by mshannaq** [php-opencloud/openstack#399]
Hello,

is there any method to get the attached volumes into server?

for example:

```
compute = $openstack->computeV2();
$server = $compute->getServer(['id' => 'server-id']);

// Get attached volumes
$volumes = $server->getVolumesAttached();

```

or how can I see if there is any volumes attached to the server?

Thanks

**Comment by k0ka** [comment]
Hello,

We have corresponding examples (and tests), but it is not covered in the documentation yet

https://github.com/php-opencloud/openstack/blob/2335c75e59b5bc6817b169c63bf74d9d7f8fc04d/samples/Compute/v2/servers/list_volume_attachments.php

**Comment by k0ka** [comment]
https://php-openstack-sdk.readthedocs.io/en/latest/services/compute/v2/volume-attachments.html
