### ISSUE TITLE
Create flavour method is missing.

### ISSUE THREAD

**Issue by haphan** [php-opencloud/openstack#45]
Hey, is there any plan to implement a method to create flavours? 

Thanks

**Comment by jamiehannaford** [comment]
@haphan I'll try to add this within the next few days.

**Comment by haphan** [comment]
Hey, if you are not already working on this, I've implemented api methods for managing flavours and ssh keypair. 

Will send a PR later.

**Comment by jamiehannaford** [comment]
@haphan :+1:

**Comment by haphan** [comment]
Fixed in #50
