### ISSUE TITLE
Verbose mode for guzzlehttp requests

### ISSUE THREAD

**Issue by jlstack** [php-opencloud/openstack#47]
In our application we are currently getting "cURL error 1: Protocol %7Bhttps not supported or disabled in libcurl." We are having a difficult time debugging this issue as we know that https is supported in our environment. We saw that guzzlehttp has a 'debug' argument but could not find a way to use this feature with the current SDK. Is this already supported or are there any intentions of supporting it in the future?

**Comment by haphan** [comment]
@jlstack Debugging is supported but not well documented. 

Following snippet will give you a good start. The most important part is you need to enable debug by setting `debugLog` to `true` and also inject `logger` and `messageFormatter`

```php
use GuzzleHttp\MessageFormatter;
use Monolog\Logger;

$logger = new Logger('console');
$messageFormatter = new MessageFormatter(MessageFormatter::DEBUG);

$params = [
    'authUrl'          => 'http://1.2.3.4:5000/v3',
    'region'           => 'REGION',
    'user'             => [],
    'debugLog'         => true,
    'logger'           => $logger,
    'messageFormatter' => $messageFormatter,
];
$openstack = new OpenStack\OpenStack($params);
```

**Comment by haphan** [comment]
@jamiehannaford I guess this issue is more of a question. Can you close?
