### ISSUE TITLE
setDefaultOption : verify ?

### ISSUE THREAD

**Issue by BorderCloud** [php-opencloud/openstack#62]
Hi

How can I set the option verify of client in your lib ?
I need to precise a custom SSL certificate on disk.

Doc Guzzle : http://docs.guzzlephp.org/en/latest/request-options.html#verify

NB : I have to use the api V3.

Thanks
Karima

**Comment by jamiehannaford** [comment]
Right now, this is not possible to do. We should definitely add this ability though, since it's a fairly standard use case. I imagine you'd pass in options as a new constructor key to the `OpenStack` builder. What do you think @haphan?

**Comment by haphan** [comment]
@jamiehannaford 👍  for having a new constructor key in `OpenCloud\Common\Service\Builder`.

Propose PR: https://github.com/php-opencloud/common/pull/3

**Comment by BorderCloud** [comment]
Hello

How to insert the option verify in this example  ?
```
require 'vendor/autoload.php';

$openstack = new OpenStack\OpenStack([
    'authUrl' => '{authUrl}',
    'region'  => '{region}',
    'user'    => [
        'id'       => '{userId}',
        'password' => '{password}'
    ],
    'scope'   => ['project' => ['id' => '{projectId}']]
]);

$images = $openstack->imagesV2()
                    ->listImages();

foreach ($images as $image) {
}
```
Thanks

**Comment by haphan** [comment]
@BorderCloud 

```php
use OpenCloud\Common\Service\Builder;

// see list of built-in Guzzle request options at GuzzleHttp\RequestOptions
$requestOptions = [
    'verify' => '/path/to/custom/ca.cert',
    'timeout' => '60'
];

$builder = new Builder([], 'OpenCloud', $requestOptions);

$openstack = new OpenStack\OpenStack($params, $builder);
```

Until @jamiehannaford is going tag `php-opencloud/common`, you will have to manually specify `php-opencloud/common: dev-master` in your `composer.json`

**Comment by jamiehannaford** [comment]
`v1.0.4` is now released

**Comment by haphan** [comment]
@jamiehannaford btw can you also tag `php-opencloud/openstack`?

**Comment by BorderCloud** [comment]
Thanks, I suppose Builder waits a list of parameters in the array because I have now messages like:

- "authUrl" is a required option
- and after, "identityService" must be specified and implement OpenCloud\Common\Auth\IdentityService

Can you give a example  with builder ? I am a newbie on openstack...

```
use OpenCloud\Common\Service\Builder;

// see list of built-in Guzzle request options at GuzzleHttp\RequestOptions
$requestOptions = [
    'verify' => '/path/to/custom/ca.cert',
    'timeout' => '60'
];

$builder = new Builder([], 'OpenCloud', $requestOptions);
$openstack = new OpenStack\OpenStack([
    'authUrl' => '{authUrl}',
    'region'  => '{region}',
    'user'    => [
        'id'       => '{userId}',
        'password' => '{password}'
    ],
    'scope'   => ['project' => ['id' => '{projectId}']]
], $builder);

$images = $openstack->imagesV2()
                    ->listImages();

foreach ($images as $image) {
}
```
Thanks
Karima

**Comment by jamiehannaford** [comment]
@haphan @BorderCloud I think we should add `requestOptions` to the OpenStack class. That could be fed into the service builder.

**Comment by haphan** [comment]
@jamiehannaford 
I agree that `requestOptions` need to pass to `OpenStack` since a HTTP client is also created here.

Regarding `requestOption`, I think it'd better to directly use `array $options['requestOptions']` to OpenStack class. This options will also be fed into `Builder`.

**Comment by haphan** [comment]
what do you think @jamiehannaford 
https://github.com/php-opencloud/openstack/pull/63
https://github.com/php-opencloud/common/pull/4

**Comment by haphan** [comment]
@BorderCloud  See my updated sample code above. You may need to run `composer update php-opencloud/openstack` to fetch latest version.

**Comment by BorderCloud** [comment]
Ok I have the version Installing php-opencloud/common (v1.0.5)
But I always the message `cURL error 7: Permission denied`

If I test with a bad file, the message is always the same... Strange...
```
$requestOptions = [
     'verify' => '/var/www/html/demo/NotExistFile.pem', // or 'NotExistFile.pem'
    'headers' => ['User-Agent' => 'PHP-OPENCLOUD/SDKv1.0']
];
```
An idea ?

**Comment by haphan** [comment]
@BorderCloud  Looks like a environment issue for me. Are you running Centos with SELINUX enabled? Reference:  https://github.com/guzzle/guzzle/issues/1001

When an invalid pem file is supplied, this is what I got:
`
Fatal error: Uncaught InvalidArgumentException: SSL CA bundle not found: /not/valid/ca.pem in /app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:331
`

**Comment by BorderCloud** [comment]
Ok without SELinux I have now the message 
```
 Client error: `POST https://keystone.....:5000/v3/auth/tokens` resulted in a `401 Unauthorized` response:
{"error": {"message": "The request you have made requires authentication.", "code": 401, "title": "Unauthorized"}}
```
A problem in the lib or in the config ?

**Comment by haphan** [comment]
Check your openstack crendential.

**Comment by haphan** [comment]
Issued resolved.
