### ISSUE TITLE
Possibility to merge with php-opencloud/common

### ISSUE THREAD

**Issue by haphan** [php-opencloud/openstack#64]
Merging with `php-opencloud/common` will simplify development process and reduce dependencies. 

Can you share what was the reason to separate sdk into 2 repositories @jamiehannaford?

**Comment by jamiehannaford** [comment]
I was thinking the exact same thing. It's a pain to manage 2 repos when 1 would do. Originally I wanted to branch out to allow more providers, but this is now unnecessary. I'm 👍  for merging.

**Comment by haphan** [comment]
Resolved in #65
