### ISSUE TITLE
Documentation on blockstorage is none

### ISSUE THREAD

**Issue by tokidoki11** [php-opencloud/openstack#66]
There is nothing on blockstorage documentation

**Comment by haphan** [comment]
@tokidoki11  Please refer to https://github.com/php-opencloud/openstack/tree/master/samples/block_storage/v2

**Comment by tokidoki11** [comment]
I think the author should consider writing on the documentation page also
since people would check it first

**Comment by haphan** [comment]
Agree. We should also consider rebuild docs upon merge to `master`. What do you think @jamiehannaford? 

http://php-opencloudopenstack.readthedocs.io/en/latest/ is outdated.

**Comment by jamiehannaford** [comment]
@haphan @tokidoki11 Yes, we should write docs for Block Storage _and_ auto-generate on master push. There should also be reference documentation, but the host it was on had some stability issues and I never got around to debugging and fixing. It's on my todo list.
