### ISSUE TITLE
Fatal error: Uncaught Error: Class 'OpenStackOpenStack' 

### ISSUE THREAD

**Issue by tokidoki11** [php-opencloud/openstack#67]
I followed tutorial here https://developer.ibm.com/recipes/tutorials/use-php-to-leverage-object-storage-for-bluemix/

It should be OpenStack\OpenStack.. my bad

But I think you should show how to define $openstack in the documentation for the starter...

PS: Please close this topic
-------------------------------------------
Fatal error: Uncaught Error: Class 'OpenStackOpenStack' 
This is my code
```
require 'vendor/autoload.php';

//Set up OpenStack configuration
$openstack = new OpenStackOpenStack([
 'authUrl' => $authUrl,
 'region' => $region,
 'user' => [
 'id' => $userId,
 'password' => $password
 ],
 'scope' => [
 'project' => ['id' => $projectId]
 ]
]);

//Get Token
$identity = $openstack->identityV3();
$token = $identity->generateToken([
 'user' => [
 'id' => $userId,
 'password' => $password
 ]
]); 

//access Keystone token Id
$tokenId = $token->getId();

$containerName = 'MyNewContainer';

//Uses the same OpenStack object created above
$service = $openstack->objectStoreV1();

$container = $service->createContainer([
 'name' => $containerName
]);
```

**Comment by haphan** [comment]
@tokidoki11 should be `new OpenStack\OpenStack `

Please refer to sample code here  https://github.com/php-opencloud/openstack/blob/master/samples/object_store/v1/containers/create.php
