### ISSUE TITLE
Creating temporary URL's

### ISSUE THREAD

**Issue by chrisnharvey** [php-opencloud/openstack#68]
Great work on this!

I was just wondering if it is at all possible to generate temporary URL's for objects in object store?

http://docs.openstack.org/juno/config-reference/content/object-storage-tempurl.html

**Comment by haphan** [comment]
@chrisnharvey Generating Temp URL is not in the scope of this SDK because there is no direct API for that.

You will need to construct URL from your code.

**Comment by chrisnharvey** [comment]
@haphan No problem at all, I'll just write my own.

**Comment by mzur** [comment]
If anyone is interested, I've implemented support for temporary URLs in my [Laravel adapter](https://github.com/mzur/laravel-openstack-swift/blob/f36c81683e8ba8c6a9eadd80f91c24f48da54284/src/TempUrlSwiftAdapter.php#L41-L61) (although it doesn't support all features yet).
