### ISSUE TITLE
Docs are either out of date or in limbo.

### ISSUE THREAD

**Issue by frankdejonge** [php-opencloud/openstack#79]
I'm currently working on the Flysystem adapter for opencloud, or at least trying to. I can't seem to find any docs on how to configure the client. I've looking in closed issues in order to see which array keys were expected but am now stuck in a "try and read exception message" loop. Apart from this being rather annoying to me, if I didn't need to do this for open source, I wouldn't take nearly the effort I am doing now. It would be great if the basic "getting started" documentation could get some love. This will help boost adoption greatly. Especially since the rackspace docs say the API used there is soon to be deprecated. Also, all the refdoc URL's don't point anywhere, so all the reference there are dead ends. Many other links don't exist anymore either, so I'm constantly hitting 404's or even non-existant URLs.

**Comment by haphan** [comment]
@frankdejonge In terms of docs, it could have been better. Here are few directions that can help you get started.

- Sample code: https://github.com/php-opencloud/openstack/tree/master/samples 
- Client parameters: https://github.com/php-opencloud/openstack/blob/master/src/OpenStack.php#L22-L36
 
Pull request to correct or improve docs/code are mostly welcome.

**Comment by frankdejonge** [comment]
@haphan are you using this with rackspace cloud files by any change, because I couldn't really see how the keys and such mapped to these settings.

**Comment by haphan** [comment]
@frankdejonge I am using this SDK with a vanilla Openstack instance (not Rackspace) in a production env. What is the issue you are encountering now?

**Comment by frankdejonge** [comment]
@haphan it's not clear which credentials I need to put forth, like tenant id/name, there's no mention of this in the rackspace interface/docs.

**Comment by jamiehannaford** [comment]
@frankdejonge As already mentioned in my e-mail, this is an SDK for OpenStack. So operators should already know their username, password, tenant ID/name and auth URL.

The docs needs to be a lot better in describing how to work with modifying the client, though. I'll try to work on this when I have time.

**Comment by bradjones1** [comment]
@jamiehannaford The documentation links in the README for this repo both seem to be broken at the moment? I'm just a little confused which documentation applies to this repo vs. the older deprecated openstack project under the rackspace namespace.

**Comment by haphan** [comment]
@bradjones1 It is readthedocs server that is unreliable at times. I randomly receive 404

- Docs for this repo: http://docs.os.php-opencloud.com/en/latest/
- Docs for sdk under rackspace: http://docs.php-opencloud.com/en/latest/

**Comment by RaySS1987** [comment]
Would someone take care to fix the links to reference documentation at http://php-opencloudopenstack.readthedocs.io/en/latest ? There are links to http://refdocs.php-opencloud.com which does not resolve at all. Also, http://docs.os.php-opencloud.com/en/latest/ which haphan posted is showing "Sorry, This page does not exist yet. ". Quite sad, considering it's a valuable resource to read.

**Comment by k0ka** [comment]
The current supported docs at https://php-openstack-sdk.readthedocs.io/en/latest
