### ISSUE TITLE
List Users

### ISSUE THREAD

**Issue by PandaNiss** [php-opencloud/openstack#82]
I want to list user but i have a error : 
Fatal error: Uncaught OpenCloud\Common\Error\BadResponseError: HTTP Error ~~~~~~~~~~ The remote server returned a "403 Forbidden" error for the following transaction: Request ~~~~~~~ GET /v3/users HTTP/1.1 User-Agent: GuzzleHttp/6.2.1 curl/7.29.0 PHP/7.0.9 Host: 192.168.1.10:5000 Response ~~~~~~~~ HTTP/1.1 403 Forbidden Date: Thu, 11 Aug 2016 13:23:45 GMT Server: Apache/2.4.6 (CentOS) Vary: X-Auth-Token x-openstack-request-id: req-2a87260a-dc17-47ab-8b85-5e8a7a79cc58 Content-Length: 136 Connection: close Content-Type: application/json Further information ~~~~~~~~~~~~~~~~~~~ Visit http://docs.php-opencloud.com/en/latest/http-codes for more information about debugging HTTP status codes, or file a support issue on https://github.com/php-opencloud/openstack/issues. in /home/admin/Documents/html/vendor/php-opencloud/common/src/Common/Error/Builder.php:134 Stack trace: #0 /home/admin/Documents/html/vendor/php-opencloud/common/src/Common/Transport/Middleware.php(29): OpenCloud\Common\Error\Builder->httpError(Object(G in /home/admin/Documents/html/vendor/php-opencloud/common/src/Common/Error/Builder.php on line 134

I don't have error in authentication because i can list project and server .. juste Users i can't list him.
someone can help please ?

**Comment by haphan** [comment]
@PandaNiss looks like your credential does not have admin right.

**Comment by PandaNiss** [comment]
yes, but I can't list my user id and name ?

**Comment by haphan** [comment]
@PandaNiss This is not an issue of SDK itself.  The api endpoint `/v3/users` requires admin privilege thus will response with `403` error regardless you're querying your own user id or not.

This role-based acccess policies are defined in `policy.json`. 

```bash
[root@localhost keystone]# cat /etc/keystone/policy.json  | grep _user
    "identity:list_user_projects": "rule:admin_or_owner",
    "identity:get_user": "rule:admin_required",
    "identity:list_users": "rule:admin_required",
    "identity:create_user": "rule:admin_required",
    "identity:update_user": "rule:admin_required",
    "identity:delete_user": "rule:admin_required",
```
 
Hope this helps.

**Comment by PandaNiss** [comment]
Okay, because I list the user's project and I thought I could also list user, but her voice that why I could list the user's project: 

"identity:list_user_projects": "rule:admin_or_owner"
"identity:list_users": "rule:admin_required"

I think it's clear, thanks
