### ISSUE TITLE
failed to connecte server code:1006

### ISSUE THREAD

**Issue by PandaNiss** [php-opencloud/openstack#84]
Hello ! I create web site with php-opencloud/Openstack and because i didn't find the api console i just insert the URL with header function in PHP :

header ('Location: http://...:6080/vnc_auto.html?token='.$tokenId.'&title='.$serverName.'('.$serverID.')');

but when i want to connected its give to me failed to connect (code:1006)

someone can give me to help please !

**Comment by jamiehannaford** [comment]
@PandaNiss this is not an SDK issue, but an issue with your code.

**Comment by PandaNiss** [comment]
but when I run the console from the platform OpenStack and I raise from my site that connects its just if I launch directly from my site as its not walking

**Comment by jamiehannaford** [comment]
What console? What do you mean by "platform OpenStack" and "raise from my site"? Sorry but I don't understand what the problem is.

**Comment by PandaNiss** [comment]
the problem is that I can't connect to the novnc console.
I haven't found any api or method to use the VNC console in the documentation but I saw that you just started creating the operations console for nova, so I'll wait until you finish and I think my problem will solve it ,
thanks

**Comment by jamiehannaford** [comment]
Okay, sounds good 👍
