### ISSUE TITLE
justinrainbow/json-schema 1.3 is getting old

### ISSUE THREAD

**Issue by nicolas-t** [php-opencloud/openstack#98]
Hello,

Why do you require such an old version (2 year old) of json-schema ?  
https://github.com/justinrainbow/json-schema/releases

Thanks

**Comment by haphan** [comment]
@nicolas-t Thanks for reporting. Feel free to create a PR for this.

**Comment by nicolas-t** [comment]
there you go:
https://github.com/php-opencloud/openstack/pull/99

:)

**Comment by haphan** [comment]
Thank you @nicolas-t.
